on: workflow_dispatch
name: 🚀 FTP-SYNC-DRY
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftp
        server-dir: www/monoraldotnet/
        #exclude:
        #  - .git*
        #  - README.txt
        dry-run: true
